
version: '3'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    restart: always
    volumes:
      - /Users/manjur/Raiz/Project/inputdata:/csvserver/inputdata
  prom:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
